Ready for shipment.

diff --git a/latc_llvm b/latc_llvm
--- a/latc_llvm
+++ b/latc_llvm
@@ -2,29 +2,14 @@
 
 if [ -e "$1" ]
 then
-  #make
-  dist/build/LatteCompiler/LatteCompiler "$1" "${1%.*}.ast" "${1%.*}.ll"
-  if [ $? -ne 0 ]
+  ./latc "$1" "${1%.*}.ast" "${1%.*}.ll"
+  if [ $? -eq 0 ]
   then
-    echo "GEN FAIL"
-  else
-    echo "GEN PASS"
+    llvm-as -o "${1%.*}_tmp.bc" "${1%.*}.ll"
+    llvm-link -o "${1%.*}.bc" "${1%.*}_tmp.bc" lib/runtime.bc
+    rm "${1%.*}_tmp.bc"
   fi
-  #cat "${1%.*}.ast"
-  llvm-as -o "${1%.*}_tmp.bc" "${1%.*}.ll"
-  llvm-link -o "${1%.*}.bc" "${1%.*}_tmp.bc" lib/runtime.bc
-  rm "${1%.*}_tmp.bc"
-  #echo "running..."
-  #echo lli "${1%.*}.bc"
-  #echo "ended..."
-  #DIFF=$(lli "${1%.*}.bc" | diff "${1%.*}.output" -)
-  #if [ "$DIFF" != "" ]
-  #then
-  #  echo "RUN FAIL"
-  #  echo $DIFF
-  #else
-  #  echo "RUN PASS"
-  #fi
 else
-  echo "Couldn't find file '$1'."
+  echo "ERROR" 1>&2
+  echo "Couldn't find file '$1'." 1>&2
 fi
